/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/apoderado/registro': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Registrar Apoderado */
    post: operations['registrar_apoderado_auth_apoderado_registro_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/apoderado/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingresar Apoderado */
    post: operations['ingresar_apoderado_auth_apoderado_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/estudiante/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ingresar Estudiante
     * @description Perfil + PIN (RF-A3). Tras varios PIN incorrectos el perfil se bloquea unos minutos:
     *     un PIN de 4 dígitos sin bloqueo se adivina en poco tiempo (modelo_base_datos.md §1).
     */
    post: operations['ingresar_estudiante_auth_estudiante_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/apoderado/estudiante': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ver Estudiante */
    get: operations['ver_estudiante_apoderado_estudiante_get'];
    put?: never;
    /** Crear Estudiante */
    post: operations['crear_estudiante_apoderado_estudiante_post'];
    delete?: never;
    options?: never;
    head?: never;
    /** Editar Estudiante */
    patch: operations['editar_estudiante_apoderado_estudiante_patch'];
    trace?: never;
  };
  '/estudiante/perfil': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ver Perfil
     * @description Alias, curso y puntos para la home (CU-6).
     */
    get: operations['ver_perfil_estudiante_perfil_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/estudiante/unidades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar Unidades
     * @description Unidades de su curso y de los anteriores, nunca de los superiores (modelo_estudiante.md
     *     §5), con estrellas, etiqueta y la unidad sugerida ya calculadas.
     */
    get: operations['listar_unidades_estudiante_unidades_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/estudiante/sesiones': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Abrir Sesion */
    post: operations['abrir_sesion_estudiante_sesiones_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/estudiante/sesiones/{sesion_id}/cierre': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cerrar Sesion */
    post: operations['cerrar_sesion_estudiante_sesiones__sesion_id__cierre_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/salud': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Salud
     * @description Confirma que la API está arriba e informa si alcanza la base de datos. No usa el LLM.
     */
    get: operations['salud_salud_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApoderadoCreado */
    ApoderadoCreado: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
    };
    /** EstudianteCambios */
    EstudianteCambios: {
      /** Alias */
      alias?: string | null;
      /** Curso */
      curso?: number | null;
      /** Pin */
      pin?: string | null;
    };
    /**
     * EstudianteNuevo
     * @description Solo datos mínimos: alias y curso (RF-A5, RNF-S2).
     */
    EstudianteNuevo: {
      /** Alias */
      alias: string;
      /** Curso */
      curso: number;
      /** Pin */
      pin: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** IngresoApoderado */
    IngresoApoderado: {
      /** Email */
      email: string;
      /** Contrasena */
      contrasena: string;
    };
    /** IngresoEstudiante */
    IngresoEstudiante: {
      /**
       * Estudianteid
       * Format: uuid
       */
      estudianteId: string;
      /** Pin */
      pin: string;
    };
    /**
     * PerfilEstudiante
     * @description Lo que la app guarda para mostrar el perfil en la pantalla de acceso.
     */
    PerfilEstudiante: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Alias */
      alias: string;
      /** Curso */
      curso: number;
      /** Puntajetotal */
      puntajeTotal: number;
    };
    /** RegistroApoderado */
    RegistroApoderado: {
      /** Email */
      email: string;
      /** Contrasena */
      contrasena: string;
    };
    /** SesionPractica */
    SesionPractica: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Inicio
       * Format: date-time
       */
      inicio: string;
      /** Fin */
      fin: string | null;
    };
    /** Token */
    Token: {
      /** Token */
      token: string;
      /**
       * Rol
       * @enum {string}
       */
      rol: 'apoderado' | 'estudiante';
    };
    /** UnidadEstudiante */
    UnidadEstudiante: {
      /** Id */
      id: string;
      /** Curso */
      curso: number;
      /** Descripcion */
      descripcion: string;
      /** Estrellas */
      estrellas: number;
      /** Etiqueta */
      etiqueta: ('dominada' | 'repasar' | 'nueva') | null;
      /** Sugerida */
      sugerida: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  registrar_apoderado_auth_apoderado_registro_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegistroApoderado'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApoderadoCreado'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  ingresar_apoderado_auth_apoderado_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IngresoApoderado'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  ingresar_estudiante_auth_estudiante_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IngresoEstudiante'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  ver_estudiante_apoderado_estudiante_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PerfilEstudiante'];
        };
      };
    };
  };
  crear_estudiante_apoderado_estudiante_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EstudianteNuevo'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PerfilEstudiante'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  editar_estudiante_apoderado_estudiante_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EstudianteCambios'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PerfilEstudiante'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  ver_perfil_estudiante_perfil_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PerfilEstudiante'];
        };
      };
    };
  };
  listar_unidades_estudiante_unidades_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnidadEstudiante'][];
        };
      };
    };
  };
  abrir_sesion_estudiante_sesiones_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SesionPractica'];
        };
      };
    };
  };
  cerrar_sesion_estudiante_sesiones__sesion_id__cierre_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sesion_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SesionPractica'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  salud_salud_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
